# Generated by Django 5.1.3 on 2024-11-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_commentanonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanonymous',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.articles'),
            preserve_default=False,
        ),
    ]
